### ISSUE TITLE
Blackboard - Month is wrong

### ISSUE THREAD

**Issue by Flozi95** [Fachschaft07/fs-web-app#17]
The month of the blackboard entries gets displayed with an offset of -1 to the right month.
![image](https://cloud.githubusercontent.com/assets/1878362/19111462/fac22294-8aff-11e6-92b4-59c024382981.png)
(The REST Api seems to work right.)

... not quite sure if this is the right project :-) ...

**Comment by FHellmann** [comment]
The reason for this issue is, that the calendar starts the month with index 0. So January is 0, February 1, and so on.

**Comment by lucaspataro** [comment]
This is fixed now, thanks for noticing :+1:
I also reversed the displayed order so the newest entry is now at the top.

**Comment by Flozi95** [comment]
:+1: no problem :wink:
